image: docker:latest

services:
  - docker:dind

stages:
  - build
  - push

before_script:
  - apk add --no-cache make

build_production:
  stage: build
  script:
    - make build-production

push_to_registry:
  stage: push
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker tag justicewatch-frontend:latest-prod registry.gitlab.com/gjkeller1/cs373-spring-2025-group-07/justicewatch-frontend:latest-prod
    - docker push registry.gitlab.com/gjkeller1/cs373-spring-2025-group-07/justicewatch-frontend:latest-prod
