image: docker:latest

services:
  - docker:dind

before_script:
  - apk add --no-cache make
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

build_production:
  stage: build
  script:
    - make build-production
    # Tag image with GitLab registry path
    - docker tag justicewatch-frontend:latest-prod registry.gitlab.com/gjkeller1/cs373-spring-2025-group-07/justicewatch-frontend:latest-prod
    # Push to GitLab registry
    - docker push registry.gitlab.com/gjkeller1/cs373-spring-2025-group-07/justicewatch-frontend:latest-prod
