services:
  frontend:
    build:
      tags:
        - registry.gitlab.com/gjkeller1/cs373-spring-2025-group-07/justicewatch-frontend:latest-staging
      args:
        ENV_FILE: .env.local
    image: registry.gitlab.com/gjkeller1/cs373-spring-2025-group-07/justicewatch-frontend:latest-staging
    env_file:
      - .env.staging
    ports:
      - "3000:3000"
    networks:
      - int
      - ext

  db:
    container_name: justicewatch-db-staging
    env_file:
      - .env.staging
    volumes:
      - db-staging:/var/lib/postgresql/data

volumes:
  db-staging:
    external: true
