services:
  frontend:
    env_file:
      - .env.prod
    ports:
      - "3000:3000"
    container_name: justicewatch-frontend-staging
  db:
    container_name: justicewatch-db-staging
    env_file:
      - .env.prod
    volumes:
      - dbdata-staging-2:/var/lib/postgresql/data

volumes:
  dbdata-staging-2:
