services:
  frontend:
    env_file:
      - .env.prod
    ports:
      - "3000:3000"
    container_name: justicewatch-frontend-staging
  db:
    container_name: justicewatch-db-staging
    env_file:
      - .env.prod
    volumes:
      - justicewatch-db-staging:/var/lib/postgresql/data

volumes:
  justicewatch-db-staging:
