services:
  frontend:
    image: justicewatch-frontend:latest-prod
    env_file:
      - .env.prod
    networks:
      - int

  nginx-proxy:
    image: nginxproxy/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - certs:/etc/nginx/certs
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    restart: always
    env_file:
      - .env.prod
    networks:
      - int
      - ext
    depends_on:
      - frontend

  acme-companion:
    image: nginxproxy/acme-companion
    container_name: nginx-proxy-acme
    volumes_from:
      - nginx-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - acme:/etc/acme.sh
    env_file:
      - .env.prod
    depends_on:
      - nginx-proxy
    restart: always
    networks:
      - int
      - ext

volumes:
  certs:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/docker/nginx/certs
      o: bind
  html:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/docker/nginx/html
      o: bind
  acme:
    driver: local
    driver_opts:
      type: none
      device: ${PWD}/docker/nginx/acme
      o: bind
