services:
  frontend:
    build:
      tags:
        - registry.gitlab.com/gjkeller1/cs373-spring-2025-group-07/justicewatch-frontend:latest-prod
    image: registry.gitlab.com/gjkeller1/cs373-spring-2025-group-07/justicewatch-frontend:latest-prod
    env_file:
      - .env.prod
    networks:
      - int

  nginx-proxy:
    image: nginxproxy/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - certs:/etc/nginx/certs
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    restart: always
    env_file:
      - .env.prod
    networks:
      - int
      - ext
    depends_on:
      - frontend

  acme-companion:
    image: nginxproxy/acme-companion
    container_name: nginx-proxy-acme
    volumes_from:
      - nginx-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - acme:/etc/acme.sh
    env_file:
      - .env.prod
    depends_on:
      - nginx-proxy
    restart: always
    networks:
      - int
      - ext

  db:
    container_name: justicewatch-db-prod
    env_file:
      - .env.prod
    volumes:
      - db-prod:/var/lib/postgresql/data

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${HOME}/.docker/config.json:/config.json
    command: --interval 30 --cleanup
    restart: always
    env_file:
      - .env.prod
    environment:
      - WATCHTOWER_NOTIFICATION_TITLE="JusticeWatch Update"
    networks:
      - int
      - ext

volumes:
  db-prod:
    external: true
  certs:
  html:
  acme:
