services:
  frontend:
    build:
      args:
        - NEXT_PUBLIC_BASE_URL=http://localhost:3000
        - NODE_ENV=production
      tags:
        - registry.gitlab.com/gjkeller1/cs373-spring-2025-group-07/justicewatch-frontend:latest-prod
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - .env.prod:/app/.env
    image: registry.gitlab.com/gjkeller1/cs373-spring-2025-group-07/justicewatch-frontend:latest-prod
    container_name: justicewatch-frontend
    env_file:
      - .env.prod
    environment:
      - VIRTUAL_HOST=justicewatch.me,www.justicewatch.me
      - LETSENCRYPT_HOST=justicewatch.me,www.justicewatch.me
      - VIRTUAL_PORT=3000
      - VIRTUAL_PATH=/
      - NEXT_PUBLIC_BASE_URL=http://localhost:3000
    networks:
      - int
      - ext

  nginx-proxy:
    image: nginxproxy/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - certs:/etc/nginx/certs
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    restart: always
    env_file:
      - .env.prod
    networks:
      - int
      - ext
    depends_on:
      - frontend
      - api

  acme-companion:
    image: nginxproxy/acme-companion
    container_name: nginx-proxy-acme
    volumes_from:
      - nginx-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - acme:/etc/acme.sh
    env_file:
      - .env.prod
    depends_on:
      - nginx-proxy
    restart: always
    networks:
      - int
      - ext
  db:
    container_name: justicewatch-db-prod
    image: postgres:17.4
    env_file:
      - .env.prod
    ports:
      - "5432:5432"
    volumes:
      - justicewatch_db-prod:/var/lib/postgresql/data
    networks:
      - int
      - ext

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${HOME}/.docker/config.json:/config.json
    command: --interval 30 --cleanup
    restart: always
    env_file:
      - .env.prod
    environment:
      - WATCHTOWER_NOTIFICATION_TITLE="JusticeWatch Update"
      - COMPOSE_PROJECT_NAME=justicewatch
    networks:
      - int
      - ext
  api:
    build:
      context: ./backend/
      dockerfile: Dockerfile
    container_name: justicewatch-api
    image: justicewatch-api:latest
    env_file:
      - .env.prod
    environment:
      - VIRTUAL_HOST=justicewatch.me,www.justicewatch.me
      - LETSENCRYPT_HOST=justicewatch.me,www.justicewatch.me
      - VIRTUAL_PORT=5002
      - VIRTUAL_PATH=/api
    depends_on:
      - db
    networks:
      - int

volumes:
  justicewatch_db-prod:
    external: true
  certs:
  html:
  acme:

networks:
  ext:
    driver: bridge
  int:
    driver: bridge
    internal: true
