version: "3.8"
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: justicewatch-frontend
    image: justicewatch-frontend:latest
    ports:
      - "3000:3000"
      - "3001:3001"
